# Generated by Django 2.1.7 on 2019-04-19 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
