# Generated by Django 2.1.7 on 2019-03-14 11:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20190314_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='postings/resize/%Y%m%d'),
        ),
    ]
