# Generated by Django 2.1.7 on 2019-03-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
